services:
  - type: worker
    name: Aurora_bot
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    buildpacks:
      - nodejs
      - python
