services:
  - type: web
    name: Aurora_bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    buildpacks:
      - url: https://github.com/render-examples/python-buildpack
